### ISSUE TITLE
Got some questions about text GCN.

### ISSUE THREAD

**Issue by Fancy7777** [plkmo/NLP_Toolkit#1]
Hi,

I have some questions regarding text GCN. Do you mind telling me your email address?

My question is that if I have multiple graphs(isolated with each other), is it possible to train with your model?

Cheers,
Derek

**Comment by plkmo** [comment]
Hi,

Sure, I have updated my email on my profile page. 

I don't see your point. If your graphs are isolated, then you will have a separate GCN for each graph. And if you somehow need to mash the outputs together to model them collectively, you can do a graph pooling for each, then sum/concat/average/pool them.
