### ISSUE TITLE
Problem installing NLP_Toolkit

### ISSUE THREAD

**Issue by johannnamr** [plkmo/NLP_Toolkit#2]
Hi there,

I was trying to install your NLP-Toolkit, but ran into difficulties getting the following error: 

![image](https://user-images.githubusercontent.com/61541813/75434444-6f1ede00-5949-11ea-8560-e8511fe5dff4.png)

Apparently, the torchvision version is not correct, but I can't install the version `torchvision==0.4.0a0+6b959ee` as it doesn't exist, but this is the one given in the "requirements.txt" file. Do you have any suggestions on how to successfully install your NLP-Toolkit?

Thank you!

**Comment by plkmo** [comment]
Hello, 
Looks like that version is missing. I have updated the dependencies, please try again thanks

**Comment by johannnamr** [comment]
That did the trick. Thanks for your help!
