### ISSUE TITLE
issues with punctuate.py

### ISSUE THREAD

**Issue by mattiaguerri** [plkmo/NLP_Toolkit#3]
issue with calinski_harabasz_score, cannot be imported
issue with google.cloud, cannot be imported
error message OSError: [E050] Can't find model 'en_core_web_lg'

In addition, add fasttext and kenlm to requirements.

**Comment by plkmo** [comment]
Thanks, added to requirements.txt.
To fix error message OSError: [E050] Can't find model 'en_core_web_lg', run:
python -m spacy download en_core_web_lg
